#!/usr/bin/env python3
"""PreToolUse (Edit|Write|MultiEdit): block hand edits to generated files.

default.project.json is generated by tools/gen_project.py and sourcemap.json by
`rojo sourcemap`. Editing them by hand gets overwritten and desyncs Studio.
Exit code 2 = block the tool call and show stderr to Claude.
"""
import json
import os
import sys

GENERATED = {
    "default.project.json": "python tools/gen_project.py",
    "sourcemap.json": "rojo sourcemap default.project.json -o sourcemap.json",
}

try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)

path = (data.get("tool_input") or {}).get("file_path") or ""
name = os.path.basename(path)
if name in GENERATED:
    print(f"{name} is generated - don't edit it by hand. Run: {GENERATED[name]}", file=sys.stderr)
    sys.exit(2)
sys.exit(0)
