--[[
	EnemyConfig (ModuleScript, Shared)
	Place inside: ReplicatedStorage > Modules

	Everything about an enemy that is not damage: hit / crit / death effects, hit sounds, the nameplate and (for mobs) the
	body and behaviour. Read by EnemyFX (client), EnemyService / DummyService (server) and the nameplate controller.

	LAYERS (each one overrides the one before, per field):
	  1. EnemyConfig.fx / .sounds                     the library of effect presets and sound entries
	  2. EnemyConfig.enemies[type].fx[preset]         an enemy type's own tweak of a preset
	  3. EnemyConfig.enemies[type].weapons[weaponType or weaponId].fx[preset]   a weapon's effect on that enemy
	Sound slots (hit / crit / crash / death) name an entry of EnemyConfig.sounds; enemies[type].sounds picks the entries and
	enemies[type].weapons[...].sounds overrides them per weapon. An empty id is skipped silently: set the ids later.

	ENEMY BEHAVIOUR AND REWARDS (EnemyService / LootService read these)
	  enemies[type].attacks = { { attack = "<id>", weight = 1, cooldown = { 3, 5 } }, ... }   ids are EnemyConfig.attacks
	  enemies[type].xp      = { skill = "Combat", amount = 40 }     granted to the killer (SkillsDataManager.AddXP, wisdom applies)
	  enemies[type].drops   = list of: { table = "<dropTables key>" }, a drop entry, or a pool (see DROPS below)

	DROPS: a drop entry is { kind = "item" | "armor" | "stat", id, count = { min, max }, chance = 0..1 }. item / armor ids
	are Items ids (armor is the same as an item, the kind only documents intent); stat entries are
	{ kind = "stat", skill = "Combat", id = "<StatisticsConfig key>", name, color = "#hex", count, chance }. Each entry rolls on its
	own; the killer's MagicFind multiplies the chance (capped at 1). A pool is { kind = "pool", chance, rolls = { 1, 1 },
	entries = { { ...drop entry..., weight } } }: it rolls `rolls` times, each picking one entry by weight.

	RECIPES
	  New attack:       add EnemyConfig.attacks.<id> = { kind = "melee", range, windup, damage, arc, recover, telegraph }.
	  New mob attack:   add the id to enemies.<key>.attacks (several entries = the mob picks by weight).
	  New drop table:   add EnemyConfig.dropTables.<name> = { entries... } and reference it with { table = "<name>" }.
	  New enemy type:   add enemies.<key> = { name, nameplate, sounds, [fx], [mob] }; spawn it with a model attribute
	                    EnemyType = "<key>" (EnemyService does that for a marker in Workspace.EnemySpawns).
	  Recolour a hit:   enemies.<key>.fx.hit_normal = { sparks = { color = { ... } } }  (only the fields you change)
	  Per-weapon look:  enemies.<key>.weapons.sword = { fx = { hit_crit = { ring = { size = 14 } } } }
	  Set a sound:      sounds.enemy_hit.id = "rbxassetid://123" (every enemy using that entry), or add a new entry
	                    and point enemies.<key>.sounds.hit at it.
	  New preset:       add it to EnemyConfig.fx; anything may play it by name (EnemyFX.play(preset, ...)).

	PRESET SHAPE (every part optional): burst (flipbook impact star), flash (starburst flare), ring (shockwave disc),
	slash (cut mark), sparks (streaks), shards (slivers), puff (smoke flipbook), motes (lingering dots), light (PointLight
	pop). Ranges are { min, max }, colors a list of Color3 (a gradient over the particle's life), sizes { start, end }.
	Textures are EnemyConfig.textures (tools/fx/gen_fx_textures.py makes them; re-upload and paste the new ids).

	  EnemyConfig.resolve(enemyType, weaponType, weaponId, preset) -> merged preset table (cached, identical table per combo)
	  EnemyConfig.sound(enemyType, weaponType, weaponId, slot)     -> sound entry or nil
	  EnemyConfig.get(enemyType)                                   -> the enemy's entry (falls back to "default")
	  EnemyConfig.levelInfo(enemyType)                             -> { level, computed, base, hpMult, damageMult, defenseMult }
	  EnemyConfig.dropsFor(enemyType)                              -> flat list of drop entries / pools
--]]

local EnemyConfig = {}

-- ===================== LIMITS (per client) =====================
EnemyConfig.limits = {
	maxLive = 26, -- effect rigs alive at once; past it normal hits are dropped (crits and deaths still play up to hardCap)
	hardCap = 40,
	targetCooldown = 0.06, -- seconds between NORMAL-hit effects on one target (stops a many-hit ability from flooding)
	maxDistance = 150, -- studs from the camera beyond which effects are skipped
	poolSize = 12, -- rigs kept ready per preset
}

-- ===================== 0. TEXTURES =====================
-- Generated by tools/fx/gen_fx_textures.py (white + alpha, tinted by each preset's colours), uploaded as images.
-- smoke and burst are 4x4 flipbooks (16 frames played once over the particle's life).
EnemyConfig.textures = {
	streak = "rbxassetid://96301713385777", -- tapered spark streak
	shard = "rbxassetid://85123166542162", -- sharp sliver
	flare = "rbxassetid://119658481753499", -- 8-point starburst flash
	ring = "rbxassetid://91930147480435", -- crisp shockwave ring
	slash = "rbxassetid://112261534443760", -- crescent cut mark
	dot = "rbxassetid://105239482007932", -- small soft mote
	smoke = "rbxassetid://88116739257838", -- flipbook: billowing puff
	burst = "rbxassetid://138960659957311", -- flipbook: spiked impact star
}

-- ===================== 1. LIBRARY: EFFECT PRESETS =====================
local WHITE = Color3.fromRGB(255, 255, 255)
local WARM = Color3.fromRGB(255, 226, 150)
local GOLD = Color3.fromRGB(255, 176, 64)
local EMBER = Color3.fromRGB(255, 120, 40)
local ICE = Color3.fromRGB(190, 240, 255)
local CYAN = Color3.fromRGB(80, 200, 255)
local BLUE = Color3.fromRGB(60, 110, 255)
local DEEP = Color3.fromRGB(30, 60, 230)
local CRIMSON = Color3.fromRGB(255, 70, 60)
local BLOOD = Color3.fromRGB(190, 25, 25)
local SALMON = Color3.fromRGB(255, 205, 190)
local DUST = { Color3.fromRGB(215, 205, 190), Color3.fromRGB(120, 112, 100) }
-- Minecraft XP greens: pale glint, green (#55FF55), dark green (#00AA00)
local XPGLINT = Color3.fromRGB(215, 255, 205)
local XPGREEN = Color3.fromRGB(85, 255, 85)
local XPDARK = Color3.fromRGB(0, 170, 0)

-- Parts of a preset (all optional): burst (flipbook impact star), flash (flare), ring (shockwave disc), slash (cut mark),
-- sparks (streaks), shards (slivers), puff (smoke flipbook), motes (lingering dots), light (PointLight pop).
EnemyConfig.fx = {
	-- a normal hit: a spiked impact flash, a hot flare, warm spark streaks and a few shards back toward the attacker
	hit_normal = {
		burst = { count = 1, color = { WHITE, WARM, GOLD }, size = { 3.2, 5.2 }, life = 0.22 },
		flash = { count = 1, color = { WHITE, WARM }, size = { 2.5, 4 }, life = 0.12, transparency = 0.1 },
		sparks = { count = 12, color = { WHITE, WARM, GOLD, EMBER }, speed = { 26, 58 }, spread = 32, life = { 0.14, 0.34 }, size = { 1.5, 0.5 }, drag = 4, gravity = 46 },
		shards = { count = 3, color = { WARM, GOLD }, speed = { 14, 30 }, spread = 40, life = { 0.2, 0.4 }, size = { 0.9, 0.4 }, drag = 3, gravity = 60 },
		puff = { count = 1, color = DUST, speed = { 0, 0 }, life = 0.45, size = { 2.2, 3.8 }, transparency = 0.45 },
		light = { color = WARM, brightness = 3, range = 9, time = 0.14 },
	},

	-- a crit: the same language, bigger and cold blue, with a crisp shockwave, a cut mark and drifting motes
	hit_crit = {
		burst = { count = 1, color = { WHITE, ICE, CYAN, BLUE }, size = { 4, 6.5 }, life = 0.28 },
		flash = { count = 1, color = { WHITE, ICE }, size = { 2.5, 4.5 }, life = 0.14, transparency = 0.15 },
		ring = { count = 1, color = { WHITE, CYAN, BLUE }, size = { 1, 6 }, life = 0.34, transparency = 0.1, speed = 0.5, horizontal = true },
		slash = { count = 1, color = { WHITE, ICE, CYAN }, size = { 2.2, 4.2 }, life = 0.16, rotation = { -35, 35 }, transparency = 0.25 },
		sparks = { count = 22, color = { WHITE, ICE, CYAN, DEEP }, speed = { 32, 80 }, spread = 38, life = { 0.2, 0.5 }, size = { 2, 0.6 }, drag = 3.5, gravity = 34 },
		shards = { count = 6, color = { ICE, CYAN, BLUE }, speed = { 16, 38 }, spread = 48, life = { 0.25, 0.5 }, size = { 1.3, 0.5 }, drag = 3, gravity = 55 },
		puff = { count = 1, color = { Color3.fromRGB(200, 225, 255), Color3.fromRGB(70, 90, 160) }, speed = { 0, 0 }, life = 0.55, size = { 2.4, 4 }, transparency = 0.55 },
		motes = { count = 14, color = { ICE, CYAN, BLUE }, speed = { 2, 9 }, spread = 180, life = { 0.7, 1.3 }, size = { 0.5, 0.05 }, drag = 2, rise = 3 },
		light = { color = CYAN, brightness = 3, range = 12, time = 0.2 },
	},

	-- a Crash hit (falling swing): the crit language in red, with a wider ground shockwave and a heavier shard spray
	hit_crash = {
		burst = { count = 1, color = { WHITE, SALMON, CRIMSON, BLOOD }, size = { 4.5, 7.5 }, life = 0.3 },
		flash = { count = 1, color = { WHITE, SALMON }, size = { 2.8, 5 }, life = 0.14, transparency = 0.15 },
		ring = { count = 1, color = { WHITE, CRIMSON, BLOOD }, size = { 1, 8 }, life = 0.38, transparency = 0.1, speed = 0.5, horizontal = true },
		slash = { count = 1, color = { WHITE, SALMON, CRIMSON }, size = { 2.4, 4.6 }, life = 0.16, rotation = { -35, 35 }, transparency = 0.25 },
		sparks = { count = 24, color = { WHITE, SALMON, CRIMSON, BLOOD }, speed = { 32, 80 }, spread = 40, life = { 0.2, 0.5 }, size = { 2, 0.6 }, drag = 3.5, gravity = 34 },
		shards = { count = 8, color = { SALMON, CRIMSON, BLOOD }, speed = { 16, 40 }, spread = 52, life = { 0.25, 0.55 }, size = { 1.4, 0.5 }, drag = 3, gravity = 55 },
		puff = { count = 1, color = { Color3.fromRGB(255, 200, 190), Color3.fromRGB(110, 40, 40) }, speed = { 0, 0 }, life = 0.55, size = { 2.6, 4.4 }, transparency = 0.55 },
		motes = { count = 14, color = { SALMON, CRIMSON, BLOOD }, speed = { 2, 9 }, spread = 180, life = { 0.7, 1.3 }, size = { 0.5, 0.05 }, drag = 2, rise = 3 },
		light = { color = CRIMSON, brightness = 3, range = 12, time = 0.2 },
	},

	-- a Full hit (swing-timing bar full): a gold edge played over the hit / crit / crash style
	hit_full = {
		flash = { count = 1, color = { WHITE, Color3.fromRGB(255, 215, 80) }, size = { 2, 3.5 }, life = 0.12, transparency = 0.2 },
		sparks = { count = 8, color = { WHITE, Color3.fromRGB(255, 240, 150), Color3.fromRGB(255, 190, 40) }, speed = { 22, 50 }, spread = 45, life = { 0.14, 0.32 }, size = { 1.4, 0.5 }, drag = 4, gravity = 40 },
		motes = { count = 6, color = { Color3.fromRGB(255, 240, 150), Color3.fromRGB(255, 190, 40) }, speed = { 2, 8 }, spread = 180, life = { 0.5, 0.9 }, size = { 0.45, 0.05 }, drag = 2, rise = 3 },
	},

	-- XP gained: a soft green flare, a ring that breathes out, motes drifting up and a few streaks (ActionBarClient plays it at the
	-- player's centre; small and short so frequent gains stay calm)
	xp_gain = {
		flash = { count = 1, color = { XPGLINT, XPGREEN }, size = { 1.8, 3 }, life = 0.2, transparency = 0.3 },
		ring = { count = 1, color = { XPGLINT, XPGREEN, XPDARK }, size = { 0.8, 4.2 }, life = 0.42, transparency = 0.4, speed = 0.5, horizontal = true },
		sparks = { count = 7, color = { XPGLINT, XPGREEN, XPDARK }, speed = { 8, 18 }, spread = 55, life = { 0.3, 0.6 }, size = { 1.1, 0.3 }, drag = 3, rise = 8 },
		motes = { count = 9, color = { XPGLINT, XPGREEN, XPDARK }, speed = { 2, 7 }, spread = 180, life = { 0.7, 1.2 }, size = { 0.4, 0.05 }, drag = 2, rise = 4 },
		light = { color = XPGREEN, brightness = 1.6, range = 9, time = 0.22 },
	},

	-- a LEVEL tick: the crit / crash language in green: a spiked star, a big flare, a wide ground shockwave, a streak fountain,
	-- shards, rising green smoke and a column of motes (played once per level, then xp_levelup_wave follows)
	xp_levelup = {
		burst = { count = 1, color = { XPGLINT, XPGREEN, XPDARK }, size = { 5, 9 }, life = 0.4 },
		flash = { count = 1, color = { XPGLINT, XPGREEN }, size = { 4, 7.5 }, life = 0.2, transparency = 0.15 },
		ring = { count = 1, color = { XPGLINT, XPGREEN, XPDARK }, size = { 1.5, 11 }, life = 0.55, transparency = 0.2, speed = 0.5, horizontal = true },
		sparks = { count = 32, color = { XPGLINT, XPGREEN, XPDARK }, speed = { 18, 44 }, spread = 70, life = { 0.4, 0.9 }, size = { 1.8, 0.5 }, drag = 3, rise = 12 },
		shards = { count = 8, color = { XPGREEN, XPDARK }, speed = { 12, 30 }, spread = 60, life = { 0.3, 0.6 }, size = { 1.2, 0.4 }, drag = 3, gravity = 30 },
		puff = { count = 4, color = { XPGREEN, XPDARK }, speed = { 2, 8 }, spread = 180, life = 0.8, size = { 3, 5.5 }, transparency = 0.55, rise = 2 },
		motes = { count = 26, color = { XPGLINT, XPGREEN, XPDARK }, speed = { 3, 12 }, spread = 180, life = { 1, 1.8 }, size = { 0.55, 0.05 }, drag = 2, rise = 5 },
		light = { color = XPGREEN, brightness = 3.5, range = 17, time = 0.4 },
	},

	-- the second wave of a level tick (a beat later): a wider, slower ring and a gentle halo, so a level lands in two pulses
	xp_levelup_wave = {
		flash = { count = 1, color = { XPGREEN, XPDARK }, size = { 3, 6 }, life = 0.28, transparency = 0.35 },
		ring = { count = 1, color = { XPGLINT, XPGREEN, XPDARK }, size = { 2, 17 }, life = 0.75, transparency = 0.3, speed = 0.5, horizontal = true },
		sparks = { count = 14, color = { XPGREEN, XPDARK }, speed = { 10, 26 }, spread = 90, life = { 0.4, 0.8 }, size = { 1.3, 0.4 }, drag = 3, rise = 9 },
		light = { color = XPDARK, brightness = 2.2, range = 14, time = 0.45 },
	},
}

-- ===================== 1b. LIBRARY: SOUNDS =====================
-- Silent until you set an id ("rbxassetid://123"). 3D at the hit point: full volume inside minDistance studs, silent
-- beyond maxDistance, so anyone nearby hears it.
EnemyConfig.sounds = {
	enemy_hit = { id = "", volume = 0.7, pitch = { 0.92, 1.08 }, minDistance = 12, maxDistance = 90 },
	enemy_crit = { id = "", volume = 0.9, pitch = { 0.95, 1.05 }, minDistance = 14, maxDistance = 100 },
	enemy_crash = { id = "", volume = 1.0, pitch = { 0.9, 1.0 }, minDistance = 16, maxDistance = 110 },
	enemy_death = { id = "", volume = 0.9, pitch = { 0.92, 1.05 }, minDistance = 16, maxDistance = 110 },
}

-- ===================== 1c. LIBRARY: ATTACKS =====================
-- kind "melee": after `windup` seconds (the mob stops, faces the target and its body flashes red) a hit lands on the target
-- if it is still within range + leeway studs and inside the `arc` degrees in front of the mob; then `recover` seconds.
-- damage is the base before the player's Defense (DamageService.hurtPlayer).
EnemyConfig.attacks = {
	melee_swing = { kind = "melee", range = 5, leeway = 1.5, windup = 0.6, damage = 10, arc = 120, recover = 0.5 },
}

-- ===================== 1c. LIBRARY: ENEMY LEVELS =====================
-- Every enemy has a level shown on its nameplate (EnemyConfig.levelInfo). With no `level` on the enemy it is computed:
--   power = health * weights.hp + bestAttackDps * weights.damage + defense * weights.defense
--   level = clamp(round(baseLevel + curve * power ^ exponent), baseLevel, maxLevel)
-- bestAttackDps = the strongest of its attacks: damage / average cooldown. Tune weights / curve here, once, for all enemies.
-- Level is cosmetic unless the enemy sets scales = true: then each level above its base level (levelScaling.baseLevel, default the
-- computed level of its written stats) adds scaling.hp / damage / defense (a fraction) to its health, attack damage and defense.
EnemyConfig.levels = {
	baseLevel = 1,
	maxLevel = 100,
	weights = { hp = 0.02, damage = 8, defense = 1.5 },
	curve = 1.2,
	exponent = 0.5,
	scaling = { hp = 0.06, damage = 0.04, defense = 0.05 },
}

-- ===================== 1d. LIBRARY: DROP TABLES =====================
-- Reference one from an enemy with { table = "<name>" }. Stats go straight to the killer's statistics when picked up.
EnemyConfig.dropTables = {
	mob_basic = {
		{ kind = "stat", skill = "Combat", id = "RottenFlesh", name = "Rotten Flesh", color = "#8B6D3F", count = { 1, 3 }, chance = 0.8 },
		{ kind = "stat", skill = "Combat", id = "Bone", name = "Bone", color = "#FFFFFF", count = { 1, 2 }, chance = 0.4 },
		{ kind = "stat", skill = "Combat", id = "String", name = "String", color = "#D9CDB8", count = { 1, 2 }, chance = 0.3 },
		{ kind = "pool", chance = 0.12, rolls = { 1, 1 }, entries = {
			{ kind = "armor", id = "iron_helmet", weight = 3 },
			{ kind = "armor", id = "iron_chestplate", weight = 2 },
			{ kind = "armor", id = "iron_leggings", weight = 3 },
			{ kind = "armor", id = "iron_boots", weight = 3 },
		} },
		{ kind = "item", id = "gold_terrafruit", count = { 1, 1 }, chance = 0.05 },
		{ kind = "item", id = "feather", count = { 1, 2 }, chance = 0.2 },
		{ kind = "item", id = "copper_ingot", count = { 1, 2 }, chance = 0.12 },
		{ kind = "item", id = "redstone", count = { 1, 3 }, chance = 0.12 },
		{ kind = "item", id = "emerald", count = { 1, 1 }, chance = 0.02 },
		{ kind = "pool", chance = 0.04, rolls = { 1, 1 }, entries = {
			{ kind = "armor", id = "golden_chestplate", weight = 2 },
			{ kind = "armor", id = "golden_leggings", weight = 3 },
			{ kind = "armor", id = "golden_boots", weight = 3 },
			{ kind = "armor", id = "diamond_helmet", weight = 1 },
		} },
	},

	-- five placeholder mobs, each with its own loot identity (stats go to the Combat statistics, items / armor to the inventory)
	slime_drops = {
		{ kind = "stat", skill = "Combat", id = "Slimeball", name = "Slimeball", color = "#55FF55", count = { 1, 3 }, chance = 0.9 },
		{ kind = "item", id = "coal_terrafruit", count = { 1, 2 }, chance = 0.25 },
		{ kind = "item", id = "slime_ball", count = { 1, 3 }, chance = 0.5 },
		{ kind = "item", id = "frostbrand", count = { 1, 1 }, chance = 0.02 },
	},
	skeleton_drops = {
		{ kind = "stat", skill = "Combat", id = "Bone", name = "Bone", color = "#FFFFFF", count = { 1, 3 }, chance = 0.9 },
		{ kind = "stat", skill = "Combat", id = "String", name = "String", color = "#D9CDB8", count = { 1, 2 }, chance = 0.4 },
		{ kind = "pool", chance = 0.1, rolls = { 1, 1 }, entries = {
			{ kind = "armor", id = "iron_helmet", weight = 3 },
			{ kind = "armor", id = "iron_chestplate", weight = 2 },
			{ kind = "armor", id = "iron_leggings", weight = 3 },
			{ kind = "armor", id = "iron_boots", weight = 3 },
		} },
		{ kind = "item", id = "iron_terrafruit", count = { 1, 1 }, chance = 0.1 },
		{ kind = "item", id = "bone", count = { 1, 3 }, chance = 0.6 },
		{ kind = "item", id = "flint", count = { 1, 2 }, chance = 0.25 },
		{ kind = "item", id = "blink_blade", count = { 1, 1 }, chance = 0.02 },
	},
	spider_drops = {
		{ kind = "stat", skill = "Combat", id = "String", name = "String", color = "#D9CDB8", count = { 1, 3 }, chance = 0.9 },
		{ kind = "stat", skill = "Combat", id = "SpiderEye", name = "Spider Eye", color = "#AA0000", count = { 1, 2 }, chance = 0.5 },
		{ kind = "item", id = "swift_gloves", count = { 1, 1 }, chance = 0.04 },
		{ kind = "item", id = "string", count = { 1, 3 }, chance = 0.6 },
		{ kind = "item", id = "spider_eye", count = { 1, 1 }, chance = 0.3 },
		{ kind = "item", id = "rabbit_foot", count = { 1, 1 }, chance = 0.03 },
		{ kind = "item", id = "phantom_membrane", count = { 1, 1 }, chance = 0.02 },
	},
	imp_drops = {
		{ kind = "stat", skill = "Combat", id = "Gunpowder", name = "Gunpowder", color = "#AAAAAA", count = { 1, 3 }, chance = 0.8 },
		{ kind = "stat", skill = "Combat", id = "BlazeRod", name = "Blaze Rod", color = "#FFAA00", count = { 1, 1 }, chance = 0.3 },
		{ kind = "stat", skill = "Combat", id = "MagmaCream", name = "Magma Cream", color = "#FF5555", count = { 1, 1 }, chance = 0.15 },
		{ kind = "item", id = "warriors_belt", count = { 1, 1 }, chance = 0.04 },
		{ kind = "item", id = "gunpowder", count = { 1, 2 }, chance = 0.5 },
		{ kind = "item", id = "blaze_rod", count = { 1, 1 }, chance = 0.2 },
		{ kind = "item", id = "glowstone_dust", count = { 1, 2 }, chance = 0.15 },
	},
	wisp_drops = {
		{ kind = "stat", skill = "Combat", id = "EnderPearl", name = "Ender Pearl", color = "#00AAAA", count = { 1, 2 }, chance = 0.4 },
		{ kind = "stat", skill = "Combat", id = "GhastTear", name = "Ghast Tear", color = "#FFFFFF", count = { 1, 1 }, chance = 0.12 },
		{ kind = "stat", skill = "Combat", id = "ShulkerShell", name = "Shulker Shell", color = "#FF55FF", count = { 1, 1 }, chance = 0.05 },
		{ kind = "item", id = "gold_terrafruit", count = { 1, 1 }, chance = 0.1 },
		{ kind = "item", id = "sapphire_amulet", count = { 1, 1 }, chance = 0.05 },
		{ kind = "item", id = "ender_pearl", count = { 1, 1 }, chance = 0.2 },
		{ kind = "item", id = "diamond", count = { 1, 1 }, chance = 0.02 },
		{ kind = "item", id = "nautilus_shell", count = { 1, 1 }, chance = 0.03 },
		{ kind = "item", id = "stormcaller", count = { 1, 1 }, chance = 0.02 },
	},
}

-- ===================== 2. ENEMY TYPES =====================
-- name        shown on the nameplate (a model attribute EnemyName overrides it)
-- nameplate   the nameplate over its head (ReplicatedStorage.GUI.EnemyNameplate). On for every enemy; false opts out
-- level       optional manual level (else computed from its stats, EnemyConfig.levels); defense optional (default 0)
-- scales      true = the level also scales health / damage / defense (levelScaling = { hp, damage, defense, baseLevel } overrides)
-- tags        list of NameplateConfig.tags ids shown as permanent chips (an element, "boss", ...); debuffs / effects are added at
--             runtime with EnemyTags.add (server)
-- sounds      slot -> key in EnemyConfig.sounds
-- fx          per-preset tweaks (layer 2); weapons[...] per-weapon tweaks (layer 3)
-- mob         present only for enemies EnemyService spawns: body / behaviour (see EnemyService)
EnemyConfig.enemies = {
	-- anything Damageable with no EnemyType attribute
	default = {
		name = "Enemy",
		nameplate = true,
		sounds = { hit = "enemy_hit", crit = "enemy_crit", crash = "enemy_crash", death = "enemy_death" },
	},

	dummy = {
		name = "Training Dummy",
		nameplate = true,
		level = 1,
		sounds = { hit = "enemy_hit", crit = "enemy_crit", crash = "enemy_crash", death = "enemy_death" },
	},

	placeholder_mob = {
		name = "Placeholder Mob",
		nameplate = true,
		tags = { "fire", "enrage" },
		sounds = { hit = "enemy_hit", crit = "enemy_crit", crash = "enemy_crash", death = "enemy_death" },
		attacks = { { attack = "melee_swing", weight = 1, cooldown = { 3, 5 } } },
		xp = { skill = "Combat", amount = 40 },
		drops = { { table = "mob_basic" } },
		mob = {
			template = "PlaceholderMob", -- ServerStorage model to clone; a tinted plain R6 rig when it does not exist
			bodyColor = Color3.fromRGB(176, 70, 70),
			health = 600,
			walkSpeed = 10,
			chaseSpeed = 14,
			aggroRange = 28, -- studs: a player this close is chased
			leashRange = 60, -- studs from home: past it the mob gives up and walks back
			stopDistance = 4, -- studs: it stops this close to its target (inside its attack range)
			hitAggroSeconds = 6, -- whoever last hit it is chased this long even outside aggroRange
			wanderRadius = 14, -- studs around home it strolls when idle
			wanderEvery = { 3, 7 }, -- seconds between strolls
			respawnSeconds = 5,
		},
	},

	slime_blob = {
		name = "Slime Blob",
		nameplate = true,
		tags = { "earth" },
		sounds = { hit = "enemy_hit", crit = "enemy_crit", crash = "enemy_crash", death = "enemy_death" },
		attacks = { { attack = "melee_swing", weight = 1, cooldown = { 3, 5 } } },
		xp = { skill = "Combat", amount = 25 },
		drops = { { table = "slime_drops" } },
		mob = {
			template = "PlaceholderMob",
			bodyColor = Color3.fromRGB(90, 200, 90),
			health = 400,
			walkSpeed = 6,
			chaseSpeed = 10,
			aggroRange = 20,
			leashRange = 60,
			stopDistance = 4,
			hitAggroSeconds = 6,
			wanderRadius = 14,
			wanderEvery = { 3, 7 },
			respawnSeconds = 5,
		},
	},
	skeleton_grunt = {
		name = "Skeleton Grunt",
		nameplate = true,
		tags = { "ice" },
		sounds = { hit = "enemy_hit", crit = "enemy_crit", crash = "enemy_crash", death = "enemy_death" },
		attacks = { { attack = "melee_swing", weight = 1, cooldown = { 2.5, 4 } } },
		xp = { skill = "Combat", amount = 45 },
		drops = { { table = "skeleton_drops" } },
		mob = {
			template = "PlaceholderMob",
			bodyColor = Color3.fromRGB(225, 225, 215),
			health = 900,
			walkSpeed = 10,
			chaseSpeed = 14,
			aggroRange = 28,
			leashRange = 60,
			stopDistance = 4,
			hitAggroSeconds = 6,
			wanderRadius = 14,
			wanderEvery = { 3, 7 },
			respawnSeconds = 5,
		},
	},
	spider_scout = {
		name = "Spider Scout",
		nameplate = true,
		tags = { "storm" },
		sounds = { hit = "enemy_hit", crit = "enemy_crit", crash = "enemy_crash", death = "enemy_death" },
		attacks = { { attack = "melee_swing", weight = 1, cooldown = { 2, 3.5 } } },
		xp = { skill = "Combat", amount = 35 },
		drops = { { table = "spider_drops" } },
		mob = {
			template = "PlaceholderMob",
			bodyColor = Color3.fromRGB(60, 40, 50),
			health = 500,
			walkSpeed = 14,
			chaseSpeed = 20,
			aggroRange = 32,
			leashRange = 60,
			stopDistance = 4,
			hitAggroSeconds = 6,
			wanderRadius = 14,
			wanderEvery = { 3, 7 },
			respawnSeconds = 5,
		},
	},
	cinder_imp = {
		name = "Cinder Imp",
		nameplate = true,
		sounds = { hit = "enemy_hit", crit = "enemy_crit", crash = "enemy_crash", death = "enemy_death" },
		attacks = { { attack = "melee_swing", weight = 1, cooldown = { 2.5, 4.5 } } },
		xp = { skill = "Combat", amount = 60 },
		drops = { { table = "imp_drops" } },
		mob = {
			template = "PlaceholderMob",
			bodyColor = Color3.fromRGB(230, 120, 40),
			health = 800,
			walkSpeed = 12,
			chaseSpeed = 16,
			aggroRange = 30,
			leashRange = 60,
			stopDistance = 4,
			hitAggroSeconds = 6,
			wanderRadius = 14,
			wanderEvery = { 3, 7 },
			respawnSeconds = 5,
		},
	},
	void_wisp = {
		name = "Void Wisp",
		nameplate = true,
		sounds = { hit = "enemy_hit", crit = "enemy_crit", crash = "enemy_crash", death = "enemy_death" },
		attacks = { { attack = "melee_swing", weight = 1, cooldown = { 3, 5 } } },
		xp = { skill = "Combat", amount = 110 },
		drops = { { table = "wisp_drops" } },
		mob = {
			template = "PlaceholderMob",
			bodyColor = Color3.fromRGB(150, 90, 220),
			health = 1400,
			walkSpeed = 9,
			chaseSpeed = 13,
			aggroRange = 26,
			leashRange = 60,
			stopDistance = 4,
			hitAggroSeconds = 6,
			wanderRadius = 14,
			wanderEvery = { 3, 7 },
			respawnSeconds = 5,
		},
	},
}

-- ===================== RESOLVING =====================
local function merge(base: any, over: any): any
	if over == nil then
		return base
	end
	if type(base) ~= "table" or type(over) ~= "table" or #over > 0 then
		return over
	end
	local out = {}
	for k, v in pairs(base) do
		out[k] = v
	end
	for k, v in pairs(over) do
		out[k] = merge(base[k], v)
	end
	return out
end

local resolved: { [string]: any } = {}

--- The flat drop list of an enemy: its `drops` with every { table = "<name>" } expanded from EnemyConfig.dropTables.
function EnemyConfig.dropsFor(enemyType: string?): { any }
	local out = {}
	for _, entry in ipairs(EnemyConfig.get(enemyType).drops or {}) do
		if entry.table then
			for _, dropped in ipairs(EnemyConfig.dropTables[entry.table] or {}) do
				table.insert(out, dropped)
			end
		else
			table.insert(out, entry)
		end
	end
	return out
end

function EnemyConfig.get(enemyType: string?): any
	return EnemyConfig.enemies[enemyType or "default"] or EnemyConfig.enemies.default
end

local levelCache: { [any]: any } = {}

--- level (shown), computed (from stats), base and hp / damage / defense multipliers for an enemy type (cached).
--- The multipliers are 1 unless the enemy sets scales = true. Server (EnemyService) and client both read this.
function EnemyConfig.levelInfo(enemyType: string?): any
	local key = enemyType or "default"
	local cached = levelCache[key]
	if cached then
		return cached
	end
	local entry = EnemyConfig.get(enemyType)
	local lv = EnemyConfig.levels
	local health = entry.mob and entry.mob.health or entry.health or 0
	local bestDps = 0
	for _, option in ipairs(entry.attacks or {}) do
		local attack = EnemyConfig.attacks[option.attack]
		if attack then
			local cooldown = option.cooldown or { 3, 5 }
			local average = math.max(((cooldown[1] or 3) + (cooldown[2] or cooldown[1] or 3)) / 2, 0.1)
			bestDps = math.max(bestDps, (attack.damage or 0) / average)
		end
	end
	local power = health * lv.weights.hp + bestDps * lv.weights.damage + (entry.defense or 0) * lv.weights.defense
	local computed = math.clamp(math.round(lv.baseLevel + lv.curve * power ^ lv.exponent), lv.baseLevel, lv.maxLevel)
	local level = math.clamp(math.floor(entry.level or computed), lv.baseLevel, lv.maxLevel)
	local scaling = entry.levelScaling or {}
	local base = scaling.baseLevel or computed
	local steps = entry.scales and math.max(level - base, 0) or 0
	local info = {
		level = level,
		computed = computed,
		base = base,
		hpMult = 1 + (scaling.hp or lv.scaling.hp) * steps,
		damageMult = 1 + (scaling.damage or lv.scaling.damage) * steps,
		defenseMult = 1 + (scaling.defense or lv.scaling.defense) * steps,
	}
	levelCache[key] = info
	return info
end

function EnemyConfig.resolve(enemyType: string?, weaponType: string?, weaponId: string?, preset: string): any
	local key = table.concat({ enemyType or "", weaponType or "", weaponId or "", preset }, "|")
	local cached = resolved[key]
	if cached then
		return cached
	end
	local enemy = EnemyConfig.get(enemyType)
	local out = EnemyConfig.fx[preset]
	out = merge(out, enemy.fx and enemy.fx[preset])
	local weapons = enemy.weapons
	if weapons then
		out = merge(out, weapons[weaponType or ""] and weapons[weaponType or ""].fx and weapons[weaponType or ""].fx[preset])
		out = merge(out, weapons[weaponId or ""] and weapons[weaponId or ""].fx and weapons[weaponId or ""].fx[preset])
	end
	resolved[key] = out
	return out
end

function EnemyConfig.sound(enemyType: string?, weaponType: string?, weaponId: string?, slot: string): any?
	local enemy = EnemyConfig.get(enemyType)
	local name = enemy.sounds and enemy.sounds[slot]
	local weapons = enemy.weapons
	if weapons then
		for _, w in ipairs({ weaponType or "", weaponId or "" }) do
			local override = weapons[w] and weapons[w].sounds and weapons[w].sounds[slot]
			if override then
				name = override
			end
		end
	end
	local entry = name and EnemyConfig.sounds[name]
	if entry and entry.id and entry.id ~= "" then
		return entry
	end
	return nil
end

return EnemyConfig
