#!/usr/bin/env python3
"""Download item icons from the Minecraft Wiki into assets/icons/.

Usage:  python tools/fetch_icons.py            # fetch every entry in ICONS
        python tools/fetch_icons.py iron_sword  # fetch only the named keys

ICONS maps our suffix-free key -> the wiki file's base name. The wiki names files
like `Iron_Sword_JE2_BE2.png` (the JE#/BE# suffix is a texture revision), so we look
the newest revision up through the MediaWiki API instead of pinning it. The result is
saved as assets/icons/<key>.png and recorded in assets/icons/SOURCES.md.

Next step: python tools/upload_icons.py (uploads and regenerates ItemIconData.lua).
Minecraft textures are Mojang's; check the wiki's license notes before shipping.
"""
import json
import os
import re
import sys
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "icons")
API = "https://minecraft.wiki/api.php"
UA = "FIA-icon-fetch/1.0 (Roblox game dev; local tool)"

# key -> wiki base name. Add a line to add an icon, then re-run both tools.
ICONS = {
    "barrier": "Barrier",  # placeholder for items without an icon
    "iron_sword": "Iron_Sword",
    "diamond_sword": "Diamond_Sword",
    "golden_sword": "Golden_Sword",
    "wooden_spear": "Wooden_Spear",
    "bow": "Bow",
    "stick": "Stick",
    "coal": "Coal",
    "iron_ingot": "Iron_Ingot",
    "gold_ingot": "Gold_Ingot",
    "iron_helmet": "Iron_Helmet",
    "iron_chestplate": "Iron_Chestplate",
    "iron_leggings": "Iron_Leggings",
    "iron_boots": "Iron_Boots",
    "golden_helmet": "Golden_Helmet",
    "elytra": "Elytra",
    "leather": "Leather",
    "lapis_lazuli": "Lapis_Lazuli",
    "lead": "Lead",
    "amethyst_shard": "Amethyst_Shard",
}


def api(**params):
    params["format"] = "json"
    req = urllib.request.Request(API + "?" + urllib.parse.urlencode(params), headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def find_file(base):
    """Newest `<base>[_(item)]_JE#[_BE#].png` that is a square raster."""
    pat = re.compile(r"^" + re.escape(base) + r"(?:_\(item\))?_JE(\d+)(?:_BE(\d+))?\.png$")
    images = []
    for prefix in (base + "_JE", base + "_(item)_JE"):  # narrow prefixes: `Leather` alone drowns in armor files
        images += api(action="query", list="allimages", aiprefix=prefix, ailimit="50", aiprop="url|size")["query"]["allimages"]
    best = None
    for img in images:
        m = pat.match(img["name"])
        if not m or img["width"] != img["height"]:
            continue
        rank = (int(m.group(1)), int(m.group(2) or 0))
        if best is None or rank > best[0]:
            best = (rank, img)
    return best[1] if best else None


def main():
    wanted = sys.argv[1:] or list(ICONS)
    os.makedirs(OUT, exist_ok=True)
    rows, failed = [], []
    for key in wanted:
        base = ICONS.get(key)
        if not base:
            print(f"unknown key: {key}")
            failed.append(key)
            continue
        img = find_file(base)
        if not img:
            print(f"MISSING {key} ({base})")
            failed.append(key)
            continue
        req = urllib.request.Request(img["url"], headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=30) as r:
            blob = r.read()
        with open(os.path.join(OUT, key + ".png"), "wb") as f:
            f.write(blob)
        page = "https://minecraft.wiki/w/File:" + img["name"]
        rows.append((key, img["name"], f'{img["width"]}x{img["height"]}', page))
        print(f"ok {key:16} <- {img['name']} ({img['width']}px)")

    # SOURCES.md covers every png currently on disk; keep old rows for keys not refetched.
    sources = os.path.join(OUT, "SOURCES.md")
    known = {}
    if os.path.exists(sources):
        for line in open(sources, encoding="utf-8"):
            parts = [p.strip() for p in line.strip().strip("|").split("|")]
            if len(parts) == 4 and parts[0] not in ("key", "---"):
                known[parts[0]] = tuple(parts)
    for row in rows:
        known[row[0]] = row
    with open(sources, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Icon sources\n\nGenerated by tools/fetch_icons.py. Minecraft textures (c) Mojang; source: minecraft.wiki.\n\n")
        f.write("| key | wiki file | size | page |\n| --- | --- | --- | --- |\n")
        for key in sorted(known):
            f.write("| " + " | ".join(known[key]) + " |\n")
    if failed:
        print("failed:", ", ".join(failed))
        sys.exit(1)


if __name__ == "__main__":
    main()
