#!/usr/bin/env python3
"""Regenerate src/Shared/Modules/Inventory/ItemIconData.lua from assets/icons/ids.json.

Adding an icon:
  1. add `key: WikiName` to ICONS in tools/fetch_icons.py and run it  (-> assets/icons/<key>.png)
  2. upload the png (serve assets/icons over http and call the Studio MCP `upload_image`,
     or upload in Creator Hub) and add `"key": "rbxassetid://..."` to assets/icons/ids.json
  3. python tools/gen_icon_data.py          (use --missing to list pngs without an id yet)
ItemIconData.lua is generated: never edit it by hand.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS = os.path.join(ROOT, "assets", "icons")
OUT = os.path.join(ROOT, "src", "Shared", "Modules", "Inventory", "ItemIconData.lua")

ids = json.load(open(os.path.join(ICONS, "ids.json"), encoding="utf-8"))
pngs = sorted(f[:-4] for f in os.listdir(ICONS) if f.endswith(".png"))
missing = [k for k in pngs if k not in ids]
stale = [k for k in ids if k not in pngs]

if "--missing" in sys.argv:
    print("\n".join(missing) or "none")
    sys.exit(0)
if missing:
    print("png without an asset id yet (upload them first):", ", ".join(missing))
if stale:
    print("ids.json entries without a png:", ", ".join(stale))

lines = ["-- GENERATED by tools/gen_icon_data.py from assets/icons/ids.json. Do not edit by hand.", "return {"]
for key in sorted(ids):
    lines.append(f'\t{key} = "{ids[key]}",')
lines.append("}")
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {len(ids)} icons -> {os.path.relpath(OUT, ROOT)}")
