#!/usr/bin/env python3
"""Regenerate src/Shared/Modules/Inventory/ItemSpriteData.lua from assets/icons/*.png + assets/icons/ids.json.

A dropped item is a thin flat sprite (the icon on both faces). The EDGE of that slab is built from small coloured strips, one
run per stretch of outer pixels that share a colour, so the side of the item shows the item's own edge colours like a
Minecraft dropped item. This script does the pixel work offline (no image access at runtime).

Output (keyed by the icon's asset id, the same string ItemIcons.resolve(def).image returns):
    ["rbxassetid://..."] = { n = 16, s = { { x, y, len, dir, 0xRRGGBB }, ... } }
  n   pixels per side of the icon's real pixel grid (the 160x160 PNGs are 16x16 art scaled up x10)
  s   edge strips: first pixel (x, y) counted from the top-left, `len` pixels long, dir 1 = top edge, 2 = bottom edge,
      3 = left edge, 4 = right edge; colour of those pixels

Sources: assets/icons (the item icons, ids.json) and assets/stat_icons (the Statistics icons used by mob loot, ids.json and the
PNGs from tools/fetch_stat_icons.py; those are 150px thumbnails, so the 16x16 art is sampled at each cell's centre).
Run it after adding or changing icons (after tools/gen_icon_data.py / tools/fetch_stat_icons.py). The output is generated: never edit it by hand.
"""
import json
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "Shared", "Modules", "Inventory", "ItemSpriteData.lua")
ALPHA_MIN = 128  # a pixel counts as solid at or above this alpha
MERGE_DIST = 60  # neighbouring edge pixels whose colours differ by less than this (RGB distance) share one strip (its average colour)


def grid_size(img: Image.Image) -> int:
    if img.size[0] % 16 != 0:
        return 16  # a thumbnail: sample the 16x16 grid at the cell centres
    """The art's real pixel grid: the smallest of 16 / 32 / 64 / full size whose nearest-neighbour upscale reproduces the image."""
    w = img.size[0]
    for n in (16, 32, 64):
        if w % n == 0:
            k = w // n
            ok = True
            px = img.load()
            for y in range(0, img.size[1], k):
                for x in range(0, w, k):
                    ref = px[x, y]
                    for dy in range(k):
                        for dx in range(k):
                            if px[x + dx, y + dy] != ref:
                                ok = False
                                break
                        if not ok:
                            break
                    if not ok:
                        break
                if not ok:
                    break
            if ok:
                return n
    return w


def strips_for(path: str):
    img = Image.open(path).convert("RGBA")
    n = grid_size(img)
    w = img.size[0]
    px = img.load()

    def cell(x: int, y: int):
        r, g, b, a = px[min(w - 1, int((x + 0.5) * w / n)), min(w - 1, int((y + 0.5) * w / n))]
        return (r, g, b) if a >= ALPHA_MIN else None

    def solid(x: int, y: int) -> bool:
        return 0 <= x < n and 0 <= y < n and cell(x, y) is not None

    def close(a, b) -> bool:
        return sum((a[i] - b[i]) ** 2 for i in range(3)) ** 0.5 < MERGE_DIST

    strips = []
    # (dir id, neighbour offset, scan along x or y)
    for d, (nx, ny), along in ((1, (0, -1), "x"), (2, (0, 1), "x"), (3, (-1, 0), "y"), (4, (1, 0), "y")):
        for line in range(n):
            run = None  # [start, length, [colours]]

            def flush():
                nonlocal run
                if run:
                    sx, sy = (run[0], line) if along == "x" else (line, run[0])
                    cols = run[2]
                    avg = tuple(round(sum(c[i] for c in cols) / len(cols)) for i in range(3))
                    strips.append((sx, sy, run[1], d, avg))
                    run = None

            for step in range(n):
                x, y = (step, line) if along == "x" else (line, step)
                colour = cell(x, y)
                exposed = colour is not None and not solid(x + nx, y + ny)
                if exposed and run and close(run[2][0], colour):
                    run[1] += 1
                    run[2].append(colour)
                    continue
                flush()
                if exposed:
                    run = [step, 1, [colour]]
            flush()
    return n, strips


SOURCES = (
    os.path.join(ROOT, "assets", "icons"),
    os.path.join(ROOT, "assets", "stat_icons"),
)


def main():
    lines = ["-- GENERATED by tools/gen_item_sprites.py from assets/icons and assets/stat_icons. Do not edit by hand.", "return {"]
    total, count, seen = 0, 0, set()
    for folder in SOURCES:
        id_file = os.path.join(folder, "ids.json")
        if not os.path.exists(id_file):
            continue
        ids = json.load(open(id_file, encoding="utf-8"))
        for key in sorted(ids):
            path = os.path.join(folder, key + ".png")
            if not os.path.exists(path) or ids[key] in seen:
                continue  # not downloaded yet, or the same asset as an icon already written (Bone is both)
            seen.add(ids[key])
            n, strips = strips_for(path)
            total += len(strips)
            count += 1
            body = ", ".join("{%d,%d,%d,%d,0x%02X%02X%02X}" % (x, y, ln, d, c[0], c[1], c[2]) for x, y, ln, d, c in strips)
            lines.append('	["%s"] = { n = %d, s = { %s } }, -- %s (%d strips)' % (ids[key], n, body, key, len(strips)))
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {count} sprites, {total} strips -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
